version: "3"

services:
  mongo-sales:
    image: mongo:latest
    container_name: mongo-sales
    networks:
      - sales-network
    ports:
      - "27017:27017"
      - "28017:27017"

  postgres-auth:
    image: postgres:11
    container_name: postgres-auth
    networks:
      - sales-network
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres-products:
    image: postgres:11
    container_name: postgres-products
    networks:
      - sales-network
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: sales-rabbit
    networks:
      - sales-network
    ports:
      - "5672:5672"
      - "25676:25676"
      - "15672:15672"

  auth-api:
    build: './auth-api'
    container_name: auth-api
    depends_on:
      - postgres-auth
      - product-api
    networks:
      - sales-network
    environment:
      - PORT=8080
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=postgres-auth
      - DB_NAME=auth-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - NODE_ENV=container
    ports:
      - 8080:8080

  product-api:
    build: './product-api'
    container_name: product-api
    depends_on:
      - postgres-products
      - rabbitMQ
    networks:
      - sales-network
    environment:
      - PORT=8081
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - DB_HOST=postgres-products
      - DB_NAME=product-db
      - DB_USER=admin
      - DB_PASSWORD=123456
      - DB_PORT=5432
      - RABBIT_MQ_HOST=sales-rabbit
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - SALES_HOST=sales-api
      - SALES_PORT=8082
    ports:
      - 8081:8081

  sales-api:
    build: './sales-api'
    container_name: sales-api
    depends_on:
      - mongo-sales
      - rabbitMQ
      - product-api
    networks:
      - sales-network
    environment:
      - PORT=8082
      - API_SECRET=YXV0aC1hcGktc2VjcmV0LWNvbnRhaW5lci0xMjM0NTY=
      - MONGO_DB_URL=mongodb://admin:123456@sales-db:27017/
      - RABBIT_MQ_URL=amqp://guest:guest@sales_rabbit:5672/
      - PRODUCT_API_URL=http://product-api:8081/api/product
      - NODE_ENV=container
    ports:
      - 8082:8082

volumes:
  pgdata1:
  pgdata2:
  mongodata:

networks:
  sales-network:
    driver: bridge
